const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');

const ffmpegPath = require('ffmpeg-static');
const { safeLog } = require('../utils/safeLog');

const execFileAsync = promisify(execFile);

let cachedDepsStatus = null;

async function getFirstLine(cmd, args, options = {}) {
  try {
    const { stdout, stderr } = await execFileAsync(cmd, args, {
      timeout: 8000,
      windowsHide: true,
      ...options
    });
    const out = String(stdout || stderr || '').trim();
    return out.split(/\r?\n/)[0] || '';
  } catch (_) {
    return '';
  }
}

async function checkYtDlpAndFfmpegAvailability() {
  if (cachedDepsStatus) return cachedDepsStatus;

  const status = {
    ok: false,
    ytDlpVersion: '',
    ytDlpPath: '',
    ffmpegVersion: '',
    ffmpegPath: ''
  };

  try {
    const youtubedl = require('youtube-dl-exec');
    const ytDlpBin = youtubedl?.constants?.YOUTUBE_DL_PATH;

    const ytDlpCandidates = [];
    const envYtDlpPath = String(process.env.YTDLP_PATH || '').trim().replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1');
    if (envYtDlpPath) ytDlpCandidates.push(envYtDlpPath);
    if (ytDlpBin && fs.existsSync(ytDlpBin)) ytDlpCandidates.push(ytDlpBin);
    ytDlpCandidates.push('yt-dlp');
    ytDlpCandidates.push('/tmp/yt-dlp');

    for (const candidate of ytDlpCandidates) {
      const versionLine = await getFirstLine(candidate, ['--version']);
      if (versionLine) {
        status.ytDlpVersion = versionLine;
        status.ytDlpPath = candidate;
        break;
      }
    }

    const ffmpegCandidates = [];
    if (ffmpegPath && fs.existsSync(ffmpegPath)) ffmpegCandidates.push(ffmpegPath);
    ffmpegCandidates.push('ffmpeg');

    for (const candidate of ffmpegCandidates) {
      const versionLine = await getFirstLine(candidate, ['-version']);
      if (versionLine) {
        status.ffmpegVersion = versionLine;
        status.ffmpegPath = candidate;
        break;
      }
    }

    status.ok = Boolean(status.ytDlpVersion) && Boolean(status.ffmpegVersion);
  } catch (err) {
    safeLog('warn', '[YouTube][yt-dlp] Falha ao checar dependências (sem detalhes sensíveis).', {
      name: err?.name,
      code: err?.code,
      message: err?.message
    });
  }

  cachedDepsStatus = status;
  return status;
}

async function ensureYtDlpAndFfmpegAvailable() {
  const status = await checkYtDlpAndFfmpegAvailability();
  if (!status.ok) {
    const err = new Error('yt-dlp/ffmpeg não está disponível no ambiente do servidor.');
    err.code = 'YTDLP_NOT_AVAILABLE';
    throw err;
  }
  return status;
}

function cookieHeaderToNetscape(cookieHeader) {
  const header = String(cookieHeader || '').trim();
  if (!header) {
    return [
      '# Netscape HTTP Cookie File',
      '# Generated by backend (do not commit).',
      ''
    ].join('\n');
  }

  const lines = [
    '# Netscape HTTP Cookie File',
    '# Generated by backend (do not commit).',
    ''
  ];

  // Domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
  // When domain/path are unknown (cookie header only), assume YouTube scope.
  for (const part of header.split(';')) {
    const piece = part.trim();
    if (!piece) continue;
    const idx = piece.indexOf('=');
    if (idx <= 0) continue;
    const name = piece.slice(0, idx).trim();
    const value = piece.slice(idx + 1).trim();
    if (!name || !value) continue;

    const domain = '.youtube.com';
    const includeSubdomains = 'TRUE';
    const cookiePath = '/';
    const secure = 'TRUE';
    const expiry = '0';

    lines.push([domain, includeSubdomains, cookiePath, secure, expiry, name, value].join('\t'));
  }

  lines.push('');
  return lines.join('\n');
}

function collectOutput(stream, maxBytes = 64 * 1024) {
  let data = '';
  let total = 0;
  return new Promise((resolve) => {
    if (!stream) return resolve('');
    stream.on('data', (chunk) => {
      if (total >= maxBytes) return;
      const buf = Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk));
      const slice = buf.slice(0, Math.max(0, maxBytes - total));
      total += slice.length;
      data += slice.toString('utf-8');
    });
    stream.on('close', () => resolve(data));
    stream.on('end', () => resolve(data));
    stream.on('error', () => resolve(data));
  });
}

async function runYtDlpToMp3({ youtubeUrl, outputMp3Path, cookieHeader, proxyUrl }) {
  const status = await ensureYtDlpAndFfmpegAvailable();

  const ytdlExec = require('youtube-dl-exec');
  const youtubedl = status.ytDlpPath ? ytdlExec.create(status.ytDlpPath) : ytdlExec;

  const tempDir = await fs.promises.mkdtemp(path.join(os.tmpdir(), 'yt-dlp-'));
  const cookieFilePath = path.join(tempDir, 'cookies.txt');

  try {
    // 1) Cookies em arquivo Netscape (evita vazar cookie em argv)
    const netscapeCookies = cookieHeaderToNetscape(cookieHeader);
    await fs.promises.writeFile(cookieFilePath, netscapeCookies, { encoding: 'utf-8', mode: 0o600 });

    // 2) Saída: yt-dlp usa template. Geramos base e esperamos ".mp3"
    const base = outputMp3Path.endsWith('.mp3') ? outputMp3Path.slice(0, -4) : outputMp3Path;
    const outTemplate = `${base}.%(ext)s`;

    const flags = {
      noPlaylist: true,
      noWarnings: true,
      format: 'bestaudio/best',
      extractAudio: true,
      audioFormat: 'mp3',
      audioQuality: '0',
      ffmpegLocation: ffmpegPath,
      output: outTemplate,
      cookies: cookieFilePath,
      // evita progress bar e ruído no stderr
      noProgress: true
    };

    if (proxyUrl) {
      flags.proxy = proxyUrl;
    }

    const subprocess = youtubedl.exec(youtubeUrl, flags, { windowsHide: true });

    // Captura stdout/stderr sem logar valores sensíveis
    const [stdout, stderr] = await Promise.all([
      collectOutput(subprocess.stdout),
      collectOutput(subprocess.stderr)
    ]);

    const exitCode = await new Promise((resolve) => {
      subprocess.once('close', (code) => resolve(code));
      subprocess.once('exit', (code) => resolve(code));
      subprocess.once('error', () => resolve(1));
    });

    if (exitCode !== 0) {
      const error = new Error('yt-dlp falhou ao baixar/converter.');
      error.code = 'YTDLP_FAILED';
      error.stdout = stdout;
      error.stderr = stderr;
      throw error;
    }

    const expected = `${base}.mp3`;
    if (!fs.existsSync(expected)) {
      const error = new Error('yt-dlp finalizou sem gerar o mp3 esperado.');
      error.code = 'YTDLP_NO_OUTPUT';
      error.stdout = stdout;
      error.stderr = stderr;
      throw error;
    }

    // Normaliza para o caminho de saída pedido
    if (expected !== outputMp3Path) {
      await fs.promises.rename(expected, outputMp3Path);
    }
  } finally {
    try {
      await fs.promises.rm(tempDir, { recursive: true, force: true });
    } catch (cleanupErr) {
      safeLog('error', '[YouTube][yt-dlp] Falha ao limpar arquivos temporários:', cleanupErr);
    }
  }
}

module.exports = {
  checkYtDlpAndFfmpegAvailability,
  runYtDlpToMp3
};
