const fs = require('fs');
const path = require('path');

async function main() {
  const input = path.join(process.cwd(), 'cookies.json');
  const output = path.join(process.cwd(), 'cookies.txt');

  if (!fs.existsSync(input)) {
    console.error('cookies.json not found in workspace root');
    process.exit(2);
  }

  const raw = await fs.promises.readFile(input, 'utf8');
  let cookies;
  try {
    cookies = JSON.parse(raw);
  } catch (err) {
    console.error('Failed to parse cookies.json:', err.message);
    process.exit(2);
  }

  const lines = ['# Netscape HTTP Cookie File', '# Generated by scripts/convertCookies.js', ''];

  for (const c of cookies || []) {
    const name = String(c?.name || '').trim();
    const value = String(c?.value || '').trim();
    if (!name || !value) continue;

    let domain = String(c?.domain || '.youtube.com').trim();
    if (!domain) domain = '.youtube.com';

    const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const pathValue = String(c?.path || '/').trim() || '/';
    const isSecureByName = name.startsWith('__Secure-') || name.startsWith('__Host-');
    const secure = (c?.secure === true || isSecureByName) ? 'TRUE' : 'FALSE';

    let expiry = 0;
    const expRaw = c?.expirationDate ?? c?.expiry ?? c?.expires;
    if (typeof expRaw === 'number' && Number.isFinite(expRaw) && expRaw > 0) {
      expiry = Math.floor(expRaw);
    } else if (typeof expRaw === 'string' && expRaw.trim()) {
      const n = Number.parseFloat(expRaw);
      if (Number.isFinite(n) && n > 0) expiry = Math.floor(n);
    }

    const httpOnly = c?.httpOnly === true;
    const domainField = httpOnly ? `#HttpOnly_${domain}` : domain;

    lines.push([domainField, includeSubdomains, pathValue, secure, String(expiry), name, value].join('\t'));
  }

  lines.push('');

  await fs.promises.writeFile(output, lines.join('\n'), { encoding: 'utf8', mode: 0o600 });
  console.log('Wrote', output);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
